blog/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.blog_title,name='blog_title'),
    path('<int:article_id>/',views.blog_article,name='blog_article'),

]

course/urls.py
from django.urls import path
from .views import AboutView,CourseListView,ManageCourseListView,CreateCourseView,DeleteCourseView,CreateLessonView, ListLessonsView,DetailLessonView,StudentListLessonView
from django.views.generic import TemplateView
app_name='course'
urlpatterns=[
    # path('about/',TemplateView.as_view(template_name='course/about.html')),
    path('about/', AboutView.as_view(), name='about'),
    path('course-list/', CourseListView.as_view(), name='course_list'),
    path('manage-course/', ManageCourseListView.as_view(), name='manage_course'),
    path('create-course/', CreateCourseView.as_view(), name="create_course"),
    path('delete-course/<int:pk>/', DeleteCourseView.as_view(), name="delete_course"),
    path('create-lesson/', CreateLessonView.as_view(),name="create_lesson"),
    path('list-lessons/<int:course_id>/', ListLessonsView.as_view(), name="list_lessons"),
    path('detail-lesson/<int:lesson_id>/', DetailLessonView.as_view(), name="detail_lesson"),
    path('lessons-list/<int:course_id>/', StudentListLessonView.as_view(), name="lessons_list")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    path('article/',include("article.urls",namespace="article")),
    path('home/',TemplateView.as_view(template_name="home.html"),name='home'),
    path('image/',include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),
]
# 对上传的静态图片设置URL路径
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

course/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
from.fields import OrderField
# Create your models here.


class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='courses_user')
    title = models.CharField(max_length=100)
    student = models.ManyToManyField(User, related_name="courses_joined",blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def save(self,*args, **kwargs):
        self.slug=slugify(self.title)
        super(Course, self).save(*args,**kwargs)

    def __str__(self):
        return self.title


def user_directory_path(instance,filename):
    return "course/user_{0}/{1}".format(instance.user.id,filename)


class Lesson(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='lesson_user')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lesson')
    title = models.CharField(max_length=200)
    video = models.FileField(upload_to=user_directory_path)
    description = models.TextField(blank=True)
    attach = models.FileField(blank=True, upload_to=user_directory_path)
    order = OrderField(blank=True, for_fields=['course'])
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return '{}.{}'.format(self.order, self.title)

course/forms.py
from django import forms
from .models import Course ,Lesson


class CreateCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields=("title","overview")


class CreateLessonForm(forms.ModelForm):
    class Meta:
        model=Lesson
        fields=['course','title','video','description','attach']

    def __init__(self,user,*args,**kwargs):
        super(CreateLessonForm, self).__init__(*args,**kwargs)
        self.fields['course'].queryset=Course.objects.filter(user=user)

course/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.base import TemplateResponseMixin
from django.views import View
from .models import Course, Lesson
from .forms import CreateCourseForm, CreateLessonForm
from django.contrib.auth.models import User
from braces.views import LoginRequiredMixin
from django.shortcuts import redirect,render,get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
import json


# Create your views here.
class AboutView(TemplateView):
    template_name = 'course/about.html'


class CourseListView(ListView):
    model = Course  # 声明数据类型
    context_object_name = 'courses'  # 声明传入模板中的变量名
    template_name = 'course/course_list.html'

    def get_queryset(self):
        qs = super(CourseListView, self).get_queryset()  # 调用父类方法
        return qs.filter(user=User.objects.filter(username='mirce'))


class UserMixin:
    def get_queryset(self):
        qs = super(UserMixin, self).get_queryset()
        return qs.filter(user=self.request.user)


class UserCourseMixin(UserMixin, LoginRequiredMixin):
    model = Course
    login_url = "/account/login/"


class ManageCourseListView(UserCourseMixin, ListView):
    context_object_name = "courses"
    template_name = "course/manage/manage_course_list.html"


class CreateCourseView(UserCourseMixin,CreateView):
    fields = ['title','overview']
    template_name = 'course/manage/create_course.html'

    def post(self, request, *args, **kwargs):
        form=CreateCourseForm(data=request.POST)
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.user=self.request.user
            new_course.save()
            return redirect("course:manage_course")
        return self.render_to_response({"form": form})


class DeleteCourseView(UserCourseMixin, DeleteView):
    # template_name = 'course/manage/delete_course_confirm.html'
    success_url = reverse_lazy('course:manage_course')

    def dispatch(self, *args, **kwargs):
        resp = super(DeleteCourseView, self).dispatch(*args,**kwargs)
        if self.request.is_ajax():
            response_data= {"result": "ok"}
            return HttpResponse(json.dumps(response_data), content_type="application/json")
        else:
            return resp


class CreateLessonView(LoginRequiredMixin,View):
    model = Lesson
    login_url = '/account/login/'

    def get(self, request, *args, **kwargs):
        form=CreateLessonForm(user=self.request.user)
        return render(request, "course/manage/create_lesson.html", {"form": form})

    def post(self,request,*args,**kwargs):
        form=CreateLessonForm(self.request.user, request.POST, request.FILES)
        if form.is_valid():
            new_lesson=form.save(commit=False)
            new_lesson.user=self.request.user
            new_lesson.save()
            return redirect("course:manage_course")


class ListLessonsView(LoginRequiredMixin,TemplateResponseMixin,View):
    login_url = '/account/login/'
    template_name = 'course/manage/list_lessons.html'

    def get(self,request,course_id):
        course=get_object_or_404(Course,id=course_id)
        return self.render_to_response({"course": course})


class DetailLessonView(LoginRequiredMixin, TemplateResponseMixin, View):
    login_url = '/account/login'
    template_name = "course/manage/detail_lesson.html"

    def get(self,request,lesson_id):
        lesson = get_object_or_404(Lesson,id=lesson_id)
        return self.render_to_response({"lesson": lesson})


class StudentListLessonView(ListLessonsView):
    template_name = "course/slist_lessons.html"

    def post(self, request, *args, **kwargs):
        course = Course.objects.get(id=kwargs['course_id'])
        course.student.add(self.request.user)
        return HttpResponse("ok")

templates/course/about.html
{% extends 'base.html' %}
{% block title %}关于网站{% endblock %}
{% block content %}
<div class="container">
<h1 class="text-center">欢迎访问</h1>
<p class="text-center">这是一个发布自己所编写的网站，供广大编程者学习交流</p>
<p class="text-center">QQ群号：12121212</p>
<h2 calss="text-center">欢迎访问</h2>
</div>
{% endblock %}

templates/course/course_list.html
{% extends 'article/base.html' %}
{% block title %}Course List{% endblock %}
{% block content %}
<div class="container">
<table class="table table-hover">
    <tr>
        <td>序号</td>
        <td>课程标题</td>
        <td>讲师</td>
        <td>发布日期</td>
    </tr>
    {% for course in courses %}
    <tr id="{{ forloop.counter }}">
        <td>{{ forloop.counter }}</td>
        <td>{{ course.title }}</td>
        <td>{{ course.user.username }}</td>
        <td>{{ course.created }}</td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

templates/course/slist_lessons.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Lesson List{% endblock %}
{% block content %}
<div class="container">
<div class="text-center">
    <h1>{{ course.title }}</h1>
    <p>课程内容列表</p>
</div>
<table class="table table-hover" style="margin-top: 10px">
    <tr>
        <td>序号</td>
        <td>内容标题</td>
        <td>概要</td>
        <td>发布日期</td>
    </tr>
    {% for lesson in course.lesson.all %}
        <tr id={{ forloop.counter }}>
        <td>{{ forloop.counter }}</td>
        <td>{{ lesson.title }}</td>
            <td>{{ lesson.description|slice:'70'|linebreaks }}</td>
            <td>{{ lesson.created|date:"Y-m-d" }}</td>
            <td></td>
        </tr>
    {% empty %}
        <p>还没有发布内容，请等待</p>
    {% endfor %}
</table>
</div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/csrf.js' %}"></script>
    <script>
    function start_learn(course_id){
        $.ajaxSetup({
            beforeSend:function(xhr,settingd){
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != ''){
                      var cookies=document.cookie.split(';')  ;
                      for (var i=0;i<cookies.length;i++){
                          if(cookie.substring(0,name.length+1)==(name+='=')){
                              cookieValue=decodeURIComponent(cookie.substring(name.length+1))
                              break;
                          }
                      }
                    }
                    return cookieValue
                        }
                        if(!(/^http:.*/.test(settings.url)||/^https:.*/.test(settings.url))){
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        }
            }
        });
        $.ajax({
            type:"POST",
            url:"{% url 'course:lesson_list' course.id %}",
            data:{'course_id':course_id},
            success:function(e){
                if(e=="ok"){
                alert("You have enroll this course.")
            }else{
                alert("Sorry,There are some mistakes.")
    }
            },
        })
    }
    </script>
{% endblock %}