article/urls.py
from django.urls import path,re_path
from . import views,list_views

app_name="article"

urlpatterns=[
    path('article-column/',views.article_column,name="article_column"),
    path('del-column/',views.del_article_column,name='del_article_column'),
    path('article-post/',views.article_post,name="article_post"),
    path('article-list/',views.article_list,name='article_list'),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.article_detail,name="article_detail"),
    path('article-del/',views.del_article,name="del_article"),
    path('redit-article/<int:article_id>/',views.redit_article,name="redict_article"),
    path('list-article-titles/',list_views.article_titles,name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/',list_views.article_detail,name="article_content"),
    path('list-article-titles/<username>/',list_views.article_titles,name="author_articles"),
]

blog/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.blog_title,name='blog_title'),
    path('<int:article_id>/',views.blog_article,name='blog_article'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    path('article/',include("article.urls",namespace="article")),
    path('home/',TemplateView.as_view(template_name="home.html"),name='home'),
    path('image/',include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),
]
# 对上传的静态图片设置URL路径
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify

class ArticleColumn(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='article_column')
    column=models.CharField(max_length=200)
    created=models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

class ArticlePost(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name="article")
    title=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200)
    column=models.ForeignKey(ArticleColumn,on_delete=models.CASCADE,related_name="article_colmn")
    body=models.TextField()
    created=models.DateTimeField(default=timezone.now)
    updated=models.DateTimeField(auto_now=True)
    def get_url_path(self):
        return reverse("article:article_content",args=[self.id,self.slug])
    class Meta:
        ordering=("title",)
        index_together=(('id','slug'),)

    def __str__(self):
        return self.title

    def save(self,*args,**kargs):
        self.slug=slugify(self.title)
        super(ArticlePost, self).save(*args,**kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail",args=[self.id,self.slug])

article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost


class ArticleColumnForm(forms.Form):
    column=forms.CharField(max_length=100)
    class Meta:
        model=ArticleColumn
        fields=("column",)
class ArticlePostForm(forms.ModelForm):
    class Meta:
        model=ArticlePost
        fields=("title","body")

article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from .forms import ArticlePostForm
from .models import ArticleColumn,ArticlePost
from .forms import ArticleColumnForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger


@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, 'column_form': column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id=request.POST["column_id"]
    try:
        line=ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd=article_post_form.cleaned_data
            try:
                new_article=article_post_form.save(commit=False)
                new_article.author=request.user
                new_article.column=request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse('1')
            except:
                return HttpResponse('2')
        else:
            return HttpResponse('3')
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form,
                       "article_columns": article_columns})


@login_required(login_url="/account/login")
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    pagintor = Paginator(articles_list,2)
    page = request.GET.get("page")
    try:
        current_page = pagintor.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = pagintor.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = pagintor.page(pagintor.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles,"page": current_page})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article=get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request,"article/column/article_detail.html", {"article": article})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id=request.POST['article_id']
    try:
        article=ArticlePost.get_objects_get(id=article_id)
        article.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')


@login_required(login_url="/account/login")
@csrf_exempt
def redit_article(request,article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, 'article/column/redit_article.html',
                      {
                          "article": article,
                          "article_columns": article_columns,
                          "this_article_form": this_article_form,
                          "this_article_column": this_article_column,
                      }
                      )
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse('1')
        except:
            return HttpResponse('2')

templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}文章栏目{% endblock %}
{% block content %}
<div>
    <p class="text-right">
        <button id="add-column" onclick="add_column()" class="btn btn-primaty">
            新建栏目
        </button>
    </p>
    <table class="table table-hover">
    <tr>
        <td>序号</td>
        <td>栏目名称</td>
        <td>操作</td>
    </tr>
    {% for column in columns %}
    <tr>
        <td>{{forloop.counter}}</td>
         <td>{{column.column}}</td>
         <td>
             <a name="edit" href="javascript:"onclick="edit_column(this,{{ column.id }})">
             <span class="glyphicon glyphicon-pencil"></span>
             </a>
             <a name="delete" href="javascript:"onclick="del_column(this,{{ column.id }})">
                 <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span>
             </a>
         </td>
    </tr>
    {% empty %}
    <p>还没有设置栏目，太懒了</p>
    {% endfor %}
    </table>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function add_column(){
    var index=layer.open({
        type: 1,
        skin: "laiui-layer-rim",
        area: ["400px", "200px"],
        title: "新增栏目",
        content: '<div class="text-center" style="margin-top:20px"> <p> 请输入新栏目名称 </p> <p> {{column_form.column}}</p> </div>',
        btn:['确定', '取消'],
            yes:function (index, layero) {
            column_name = $('#id_column').val();
            $.ajax(
                {
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: {"column": column_name},
                    success: function (e) {
                        if (e == 1) {
                            parent.location.reload();
                            layer.msg("good",{icon:1});
                        } else {
                            layer.msg("此栏目已有，请更换名称",{icon:2});
                        }
                    },
                }
            );
        },

        btn2:function(index, layero) {
            layer.close(index);
        }
    }
         );
         }
function del_column(the,column_id){
        var name=$(the).parents("tr").children("td").eq(1).text();
        layer.open(
            {
                type:1,
                skin:"layui-layer-rim",
                area:["400px","200px"],
                title:"删除栏目",
                content:'<div class="text-center" style="margin-top:20px"><p>是否确定删除'+name+'栏目</p></div>',
                btn:['确定','取消'],
                yes:function(){
                    $.ajax({
                        url:'{% url "article:del_article_column" %}',
                        type:"POST",
                        data:{"column_id":column_id},
                        success:function (e) {
                            if(e=='1'){
                            parent.location.reload();
                            layer.msg("本记录已经删除");}
                            else{
                                layer.msg("删除失败");
                            }
                        },
                        })
                },
            });
}
</script>
{% endblock %}

templates/article/column/article_detail.html
{% extends base.html %}
{% load staticfiles %}
{% block title %} article list {% endblock %}
{% block content %}
    <div>
    <header>
    <h1>{{ article.title }}</h1>
        <p><a href="{% url 'article:author_articles' article.author.username %}" >{{ user.username }}</a></p>
    </header>
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css'%}"/>
    <div class="editormd-view">
        <textarea id="append-test" style="display:none;">
{{ article.body }}
            </textarea>
    </div>
    </div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script type="text/javascript">
    $(function(){
        editormd.markdownToHTML("editoemd-view",{
            htmlDecode:"style,script,iframe",
            emoji:true,
            taskList:true,
            tex:true,
            flowChart:true,
            sequenceDjagram:true,
        });
    });
    </script>
{% endblock %}

templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} article list {% endblock %}
{% block content %}
    <div>
    <table class="table table-hover">

        <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>操作</td>
        </tr>
        {% for article in articles %}
        <tr id={{ article.id }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td><a name="edit" href="{% url 'article:redit_article' article.id %}"><span class="glyphicon glyphicon-pencil"></span></a> </td>
        </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}
article column
{% endblock %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% block content %}
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">
        <div class="row" style="margin-top:10px">
                <div class="col-md-2 text-right">
                <span>标题:</span>
            </div>
            <div class="col-md-10 text-left">
                {{ article_post_form.title }}
            </div>
        </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-left"><span>栏目:</span></div>
                <div class="col-md-10 text-right">
                    <select id="which_column">
                        {% for column in article_columns %}
                            <option value="{{ column.id }}">{{ column.column }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row" style="margin-top:10px">
                <div class="col-md-2 text-right">
                    <span>内容:</span>
                </div>
               <div id="editormd" class="col-md-10 text-left">
                   <textaera style="display:none;" id="id_body"></textaera>
               </div>
            </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
        </div>
    </form>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function publish_article(){
        var title=$("#id_title").val();
        var column_id=$("#which_column").val();
        var body=$("#id_body").val()
        $.ajax({
            url:"{% url 'article:article_post' %}",
            type:"POST",
            data:{"title":title,"body":body,"column_id":column_id},
            success:function(e){
                if(e=='1'){
                    layer.msg("successful");
                }else if(e=='2'){
                    layer.msg("sorry");
                }else{
                    layer.msg("项目名称必须填写，不能为空");
                }
            },
            });
    }
</script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript">
    $(function(){
        var editor =editormd("editormd",{
            width:"100%",
            height:640,
            syncScrolling:"single",
            path:"{% static 'editor/lib/' %}"
        });
    });
    </script>
{% endblock %}

templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
    <div class="container">
    <div style="margin-left: 10px;">
        <form class="form-horizontial" action="." method="post">
            {% csrf_token %}
            <div class="row" style="margin-top:10px;">
                <div class="col-md-2 text-right"><sapn>标题：</sapn></div>
                <div class="col-md-10" text="left">{{ this_article_form.title }}</div>
            </div>
            <div class="row" style="margin-top:10px;">
                <div class="col-md-2 text-right"><sapn>栏目：</sapn></div>
                <div class="col-md-10" text="left">
                    <select id="which_column">
                        {% for column in article_columns %}
                        {% if column == this_article_column.column %}
                            <option value="{{ column.id }}" selected="selected">
                            {{ column.column }}
                            </option>
                            {% else %}
                            <option value="{{ column.id }}"selected="selected">
                            {{ column.column }}
                            </option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="row" style="margin-top:10px;">
                    <div class="col-md-2 text-right"><sapn>内容：</sapn></div>
                    <div id="editormd" class="col-md-10" text="left">
                        <textaera style="display: none;" id="id_body">
                        {{ article.body }}
                    </textaera>
                    </div>
                </div>
            <div class="row">
                <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="redit_article()">
            </div>
            </div>
        </form>
    </div>
    </div>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
    <script type="text/javascript">
    $(function(){
        var editor=editormd("editormd",{
            width:"100%",
            height:640,
            path:"{% static 'editor/lib/' %}",
        });
    });
    function redit_article(){
        var title=$("#id_title").val();
        var column_id=$("#which_column").val();
        var body=$("#id_body").val();
        $.ajax({
            url:"{% url 'article:redit_article' article.id %}",
            type:"POST",
            data:{"title":title,"body":body,"column_id":column_id},
            success:function(e){
                if (e==1){
                    layer.msg("successful");
                    location.href="{% url 'article:article_list' %}";
                }
                else{
                    layer.msg("sorry");
                }
            },
        });
    }
    </script>
{% endblock %}