account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from.import views
app_name="account"
urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html'),name='user_login'),
    path('logout/',auth_views.LogoutView.as_view(),name='user_logout'),
    path('register/',views.register,name='user_register'),
    path('password-change/',auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html",success_url="/account/password-change-done/"),name="password_change"),
    path('password-change-done/',auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"),name='password_change_done'),
    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name="account/password_reset_form.html",
        email_template_name="account/password_rest_email.html",
        success_url='/account/password-rest-done/'),
         name='password_reset'),
    path('password/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",success_url='/account/password-reset-complete/'),
         name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),name='password_reset_password'),
    path('my-information/',views.myself,name="my_information"),
    path('edit-my-information/',views.myself_edit,name="edit_my_information"),
    path('my-image/',views.my_image,name="my_image")
]

article/urls.py
from django.urls import path,re_path
from . import views,list_views

app_name="article"

urlpatterns=[
    path('article-column/',views.article_column,name="article_column"),
    path('del-column/',views.del_article_column,name='del_article_column'),
    path('article-post/',views.article_post,name="article_post"),
    path('article-list/',views.article_list,name='article_list'),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.article_detail,name="article_detail"),
    path('article-del/',views.del_article,name="del_article"),
    path('redit-article/<int:article_id>/',views.redit_article,name="redict_article"),
    path('list-article-titles/',list_views.article_titles,name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/',list_views.article_detail,name="article_content"),
    path('list-article-titles/<username>/',list_views.article_titles,name="author_articles"),
]

blog/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.blog_title,name='blog_title'),
    path('<int:article_id>/',views.blog_article,name='blog_article'),

]

course/urls.py
from django.urls import path
from .views import AboutView,CourseListView,ManageCourseListView,CreateCourseView,DeleteCourseView,CreateLessonView, ListLessonsView,DetailLessonView,StudentListLessonView
from django.views.generic import TemplateView
app_name='course'
urlpatterns=[
    # path('about/',TemplateView.as_view(template_name='course/about.html')),
    path('about/', AboutView.as_view(), name='about'),
    path('course-list/', CourseListView.as_view(), name='course_list'),
    path('manage-course/', ManageCourseListView.as_view(), name='manage_course'),
    path('create-course/', CreateCourseView.as_view(), name="create_course"),
    path('delete-course/<int:pk>/', DeleteCourseView.as_view(), name="delete_course"),
    path('create-lesson/', CreateLessonView.as_view(),name="create_lesson"),
    path('list-lessons/<int:course_id>/', ListLessonsView.as_view(), name="list_lessons"),
    path('detail-lesson/<int:lesson_id>/', DetailLessonView.as_view(), name="detail_lesson"),
    path('lessons-list/<int:course_id>/', StudentListLessonView.as_view(), name="lessons_list")
]

image/urls.py
from django.urls import path
from . import views
app_name='image'
urlpatterns=[
    path('list-images/',views.list_images,name="list_images"),
    path('upload-image/',views.upload_image,name="upload_image"),
    path('del-image/',views.del_image,name="del_image"),
    path('images/',views.falls_images,name="falls_images"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('account/',include('account.urls',namespace='account')),
    path('article/',include("article.urls",namespace="article")),
    path('home/',TemplateView.as_view(template_name="home.html"),name='home'),
    path('image/',include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),
]
# 对上传的静态图片设置URL路径
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content=""width="device-width,intial-scale=1">
    <title>{%block title %}{%endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
{% include "header.html" %}
<div class="container">
    {% block content %} {% endblock %}
</div>
{% include "footer.html" %}
{% block javascript %}{% endblock %}
</body>
</html>

templates/footer.html
<div class="containerr">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com">
                <img src="{% static '/imgs/logo.png' %}" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %} }">Home</a></li>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a> </li>
                <li><a href="{% url 'image:falls_images' %}">美图</a></li>
                <li><a href="{% url 'course:about' %}">关于</a></li>
                <li><a href="{% url 'course:course_list' %}">课程</a></li>
                <li><a href="{% url 'course:manage_course' %}">课程管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
    <div class="dropdown" style="margin_top:8px">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">
            {{user.username}}
            <span class="caret"></span>
        </button>

    <ul class="dropdown-menu">
        <li><a href="{% url 'account:password_change' %}">修改密码</a> </li>
        <li><a href="{% url 'account:edit_my_information' %}">修改信息</a></li>
    </ul>
                </div>
</li>
                <li><a href="#">{{user.username}}</a> </li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a> </li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a> </li>
                    <li><a href="{% url 'account:user_register' %}">Sign up</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home Page {% endblock %}
{% block content %}
<div class="text-center">
    <h1>WELCOME YOU</h1>
    <h3>Life is short.You need Python</h3>
    <h2>Django make it easier to build better Web apps more quickly and with less code </h2>
    {% load staticfiles %}
    <img src="{% static 'images/book.jpg' %}">
</div>
{% endblock %}

templates/pagintor.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="{{ pages.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="{{ page.next_page_number }}"> Next </a>
    {% endif %}
    </span>
</div>